### ISSUE TITLE
Problema samba 4 dns

### ISSUE THREAD

**Issue by leonardojrj** [linuxbrasil/forum#1]
Boa noite, não estou conseguindo ingressar maquina windows pelo samba ad usando SAMBA_INTERNAL
resolv.conf 
domain smb.local
search smb.local
nameserver 192.168.25.9
nameserver 192.168.25.1

hosts
192.168.25.9	localhost
192.168.25.9	controlador-samba controlador-samba.smb.local
hostname
controlador-samba

smb.conf
# Global parameters
[global]
        workgroup = SMB
        realm = SMB.LOCAL
        netbios name = TESTE-SAMBA
        server role = active directory domain controller
        dns forwarder = 8.8.8.8
        server services = s3fs rpc nbt wrepl ldap cldap
        kdc drepl winbind ntp_signd kcc dnsupdate dns

[netlogon]
        path = /var/lib/samba/sysvol/smb.local/scripts
        read only = No

[sysvol]
        path = /var/lib/samba/sysvol
        read only = No

**Comment by rmsaitam** [comment]
Instalou o pacotes `winbind, libpam-winbind libnss-winbind` ?

No setup do Kerberos solicitou conforme segue?
Reino por omissão do Kerberos versão 5: SEUDOMINIO.INT 
No meu caso, coloquei SAITAM.INT 
Servidores Kerberos para seu realm: 127.0.0.1 
Servidor administrativo para seu realm Kerberos: 127.0.0.1 

Provisionou o Samba 4 como AD?
```# samba-tool domain provision --use-rfc2307 --interactive ```

Maiores esclarecimentos detalhados, no howto https://mundodacomputacaointegral.blogspot.com.br/2016/12/instalando-configurando-e-provisionando-samba4-como-controlador-dominio-AD.html

**Comment by leonardojrj** [comment]
segui alguns passo, resolveu uns problemas que estava tendo, só que em um dns roteador ele não acha servidor samba, agora criei uma rede interna só duas maquinas pinga normal pelo dominio e ja abriu tela pra ingressar dominio.

pergunta, como saber samba rodar em uma rede que tem um dns como roteador?

uso samba_internal e não bind9_dlz

**Comment by rmsaitam** [comment]
Adiciona o DNS do Samba Internal no roteador.
