### ISSUE TITLE
duvidas acl

### ISSUE THREAD

**Issue by leonardojrj** [linuxbrasil/forum#2]
Bom dia, uma duvida, para que a acl funciona no samba é preciso criar um grupo no linux e mesmo grupo no samba-tool? e ai sim aplicar setfacl neste grupo no linux?

pergunto pq estou com problema permissão no ad, encherga compartilhamento mais não consigo mudar nada permissão

**Comment by rmsaitam** [comment]
No arquivo smb.conf incluiu a linha correspondente ao grupo de acesso?
```valid users = @nomegrupocriadoLinux```

Adicionar os usuários nesse grupo também.

Para adicionar ACL usa-se: **setfacl** e **getfacl**
Necessário instalar o pacote **acl**
**setfacl:** inclui as permissões adicionais nas pastas do sistemas
**getfacl:** lê as permissões adicionais do diretório compartilhado no Samba

Ex: aplicar permissão de leitura e execução adicionais ao diretório raiz para todos os grupos
```# setfacl -m g:nomegrupo:r-x /caminho-diretorio-path-samba```
